// simple try:catch promise
try {
  console.log("threed index.js loaded")
} catch (err) {
  // an error has occurred. no output is being attempted here.
  // console.log("threed index.js not loaded")
}
